<<<<<<< HEAD
collections:
  authors:
    output: true
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
=======
theme: jekyll-theme-slate
title: yogae
description: 정리
include:
  - README.md
>>>>>>> b8b9ce3d1d1b74f7e672148af93af7aa9124b786
